export const INIT_TASKS = "INIT_TASKS";
export const ADD_TASK = "ADD_TASK";
export const DELETE_TASK = "DELETE_TASK";
export const OPEN_ACCORDION = "OPEN_ACCORDION";

export const INIT_COMPLETED_TASKTS = "INIT_COMPLETED_TASKTS";
export const DELETE_COMPLETED_TASK = 'DELETE_COMPLETED_TASK';
